### ISSUE TITLE
Update for the latest version?

### ISSUE THREAD

**Issue by nixzhu** [minsOne/KakaoSDK-SwiftPM#2]
The latest version is 2.4.0 https://developers.kakao.com/docs/latest/en/sdk-download/ios

**Comment by nixzhu** [comment]
PR for KakaoSDK 2.4.1 https://github.com/minsOne/KakaoSDK-SwiftPM/pull/3

**Comment by minsOne** [comment]
Sorry, I so late.
SDK is updated 2.5.3.
